apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pelican

resources:
  - resources/namespace.yml
  - resources/mysql.yml
  - resources/wings.yml
  - resources/pelican.yml

configMapGenerator:
  - name: pelican-config
    envs:
      - config/panel.env

secretGenerator:
  - name: mysql-config
    envs:
      - config/mysql.env

images:
  - name: ghcr.io/shiipou/pelican-k8s/panel
    newTag: main
